title: Gabriel de Rezende GonÃ§alves
default_lang: pt-BR
favicon: "favicon.ico"

email:
  english: "hello@gabireze.com.br"
  portuguese: "contato@gabireze.com.br"

social_medias:
  - name: LinkedIn
    link: "https://linkedin.com/in/gabireze"
    emoji: "ğŸ”—"
  - name: GitHub
    link: "https://github.com/gabireze"
    emoji: "ğŸ™"
  - name: Twitter
    link: "https://twitter.com/gabireze_"
    emoji: "ğŸ¦"
  - name: Medium
    link: "https://gabireze.medium.com/"
    emoji: "âœï¸"

contribution_methods:
  - name: PayPal
    link: "https://www.paypal.com/donate/?business=S34UMJ23659VY"
    emoji: "ğŸ¦"
  - name: PicPay
    link: "https://app.picpay.com/user/gabireze"
    emoji: "ğŸª™"
  - name: PIX
    emoji: "ğŸ’µ"
    value: contato@gabireze.com.br
    extra: or [QR Code](https://gabireze.com.br/nubank){:target="_blank"}
  - name: BTC
    emoji: "ğŸ’¸"
    value: "bc1qqqtwl0akq535w3g4z0dgmq8nk0e8tqjtc2gw3x"
  - name: ETH
    emoji: "ğŸ’°"
    value: "0x954D8a59B21Cf87965D7ADBf115f930DD81C94fB"
  - name: ERC20 / BSC / Polygon
    emoji: "ğŸ”¥"
    value: "0x93b864efBc8f80cB04EF845BC1E2eB4D76c257bD"
  - name: Lightning Network
    emoji: "âš¡ï¸"
    value: lightning@gabireze.com.br
    extra: or [https://zbd.gg/gabireze](https://zbd.gg/gabireze){:target="_blank"}

markdown: kramdown
footer: true

sass:
  style: compressed
  sass_dir: _sass

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

nav:
  - name_pt: "PortuguÃªs"
    name_en: "PortuguÃªs"
    link_pt: "/"
    link_en: "/"
  - name_pt: "English"
    name_en: "English"
    link_pt: "/en"
    link_en: "/en"
  - name_pt: "LinkedIn"
    name_en: "LinkedIn"
    link_pt: "https://linkedin.com/in/gabireze/"
    link_en: "https://linkedin.com/in/gabireze/"
    link: "https://linkedin.com/in/gabireze/"
  - name_pt: "Contato"
    name_en: "Contact"
    link_pt: "contato"
    link_en: "contact-information"

include: [".well-known"]
